// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeqqsRo_JKW4KRtORwJObDkMLHj_hl8_A',
    appId: '1:816250776427:web:8855468972e72412477a2e',
    messagingSenderId: '816250776427',
    projectId: 'push-notifications-task',
    authDomain: 'push-notifications-task.firebaseapp.com',
    storageBucket: 'push-notifications-task.appspot.com',
    measurementId: 'G-RX113HMYZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPI8fvURklBWLYICywQUh9OqZoLkg1cPs',
    appId: '1:816250776427:android:748495e2cb24866b477a2e',
    messagingSenderId: '816250776427',
    projectId: 'push-notifications-task',
    storageBucket: 'push-notifications-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBY5vwHdcndoJJGS_tQ4s3um2oqIb-wGA',
    appId: '1:816250776427:ios:abb61f0c243246d5477a2e',
    messagingSenderId: '816250776427',
    projectId: 'push-notifications-task',
    storageBucket: 'push-notifications-task.appspot.com',
    iosBundleId: 'com.example.task1PushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBY5vwHdcndoJJGS_tQ4s3um2oqIb-wGA',
    appId: '1:816250776427:ios:abb61f0c243246d5477a2e',
    messagingSenderId: '816250776427',
    projectId: 'push-notifications-task',
    storageBucket: 'push-notifications-task.appspot.com',
    iosBundleId: 'com.example.task1PushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeqqsRo_JKW4KRtORwJObDkMLHj_hl8_A',
    appId: '1:816250776427:web:aa6b821f769cf62a477a2e',
    messagingSenderId: '816250776427',
    projectId: 'push-notifications-task',
    authDomain: 'push-notifications-task.firebaseapp.com',
    storageBucket: 'push-notifications-task.appspot.com',
    measurementId: 'G-3ZBD1EVH0M',
  );
}
